- name: Ping Servers 
  hosts: all
  become: yes

  tasks:    
  
  - name: Task ping
    ping:

  - name: Install nginx
    apt:
      pkg: nginx
      state: present
      
  - name: Copy
    copy: src=/root/ansible/index.html dest=/var/www/html  